export const POKEMON_ACTION_TYPES = {
  GET_POKEMON_BY_ID: "@pokemon/GET_POKEMON_BY_ID",
  GET_POKEMON_BY_ID_FAILURE: "@pokemon/GET_POKEMON_BY_ID_FAILURE",
  GET_POKEMON_BY_ID_SUCCESS: "@pokemon/GET_POKEMON_BY_ID_SUCCESS",

  GET_POKEMON_BY_NAME: "@pokemon/GET_POKEMON_BY_NAME",
  GET_POKEMON_BY_NAME_FAILURE: "@pokemon/GET_POKEMON_BY_NAME_FAILURE",
  GET_POKEMON_BY_NAME_SUCCESS: "@pokemon/GET_POKEMON_BY_NAME_SUCCESS",

  GET_POKEMON_LIST_BY_TYPE: "@pokemon/GET_POKEMON_LIST_BY_TYPE",
  GET_POKEMON_LIST_BY_TYPE_FAILURE: "@pokemon/GET_POKEMON_LIST_BY_TYPE_FAILURE",
  GET_POKEMON_LIST_BY_TYPE_SUCCESS: "@pokemon/GET_POKEMON_LIST_BY_TYPE_SUCCESS",
};
